const dados = {
  eventos: [
    {
      id: 1,
      titulo: "Entrevista - TechSolutions Ltda",
      descricao: "Entrevista para a vaga de Estágio em Desenvolvimento Web.",
      data: "2025-05-12",
      hora: "10:00",
      tipo: "entrevista",
      vaga_id: 1,
      modalidade: "Online",
      status: "confirmado",
    },
    {
      id: 2,
      titulo: "Prazo de Candidatura - DataMind S.A.",
      descricao:
        "Último dia para envio de currículo para a vaga de Análise de Dados.",
      data: "2025-05-15",
      hora: "23:59",
      tipo: "prazo",
      vaga_id: 2,
      modalidade: "Remoto",
      status: "pendente",
    },
    {
      id: 3,
      titulo: "Entrevista - Criativa Agency",
      descricao: "Entrevista técnica para a vaga de UX/UI Design.",
      data: "2025-05-20",
      hora: "14:00",
      tipo: "entrevista",
      vaga_id: 3,
      modalidade: "Presencial",
      status: "confirmado",
    },
    {
      id: 4,
      titulo: "Teste Técnico - TechSolutions Ltda",
      descricao: "Realização de teste técnico de desenvolvimento web.",
      data: "2025-05-22",
      hora: "09:00",
      tipo: "teste",
      vaga_id: 1,
      modalidade: "Online",
      status: "pendente",
    },
    {
      id: 5,
      titulo: "Resultado - DataMind S.A.",
      descricao:
        "Divulgação do resultado do processo seletivo de Análise de Dados.",
      data: "2025-05-28",
      hora: "18:00",
      tipo: "resultado",
      vaga_id: 2,
      modalidade: "Remoto",
      status: "pendente",
    },
    {
      id: 6,
      titulo: "Início do Estágio - Criativa Agency",
      descricao: "Primeiro dia de estágio na Criativa Agency.",
      data: "2025-06-02",
      hora: "08:00",
      tipo: "inicio",
      vaga_id: 3,
      modalidade: "Presencial",
      status: "pendente",
    },
  ],
};
